name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 08 * * *'

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull the Docker image
      run: docker pull mcr.microsoft.com/dotnet/framework/aspnet:4.8
      
    - uses: actions/checkout@v3
    - name: tag the Docker image
      run: docker tag mcr.microsoft.com/dotnet/framework/aspnet:4.8  rizzkhan1/aspnet:4.8

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: tag the Docker image
      run: docker push  rizzkhan1/aspnet:4.8
