name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull the Docker image
      run: docker pull mcr.microsoft.com/dotnet/framework/aspnet:4.8.1

